version: "3"

services:
  php:
    build: ./docker/php
    restart: always
    tty: true
    container_name: docker-php8-php
    ports:
      - "9000:9000"
    volumes:
      - .:/home/app

  nginx:
    build: ./docker/nginx
    container_name: docker-php8-nginx
    restart: always
    tty: true
    depends_on:
      - php
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - .:/home/app

  #  apache:
  #    build: ./docker/apache
  #    restart: always
  #    container_name: docker-php8-apache
  #    depends_on:
  #      - php
  #      - mariadb
  #    ports:
  #      - '80:80'
  #      - '443:443'
  #    volumes:
  #      - .:/home/app

  #  mariadb:
  #    image: mariadb
  #    tty: true
  #    restart: always
  #    container_name: docker-php8-mariadb
  #    ports:
  #      - '3306:3306'
  #    volumes:
  #      - './docker/mysql/config/mariadb.cnf:/etc/mysql/conf.d/custom.cnf:ro'
  #      - './docker/mysql/database:/var/lib/mysql'
  #    environment:
  #      - MYSQL_PASSWORD=root
  #      - MYSQL_ROOT_PASSWORD=root
  #      - MYSQL_DATABASE=development

  mysql:
    image: mysql:8
    tty: true
    restart: always
    container_name: docker-php8-mysql
    ports:
      - "3306:3306"
    volumes:
      - "./docker/mysql/config/mysql.cnf:/etc/mysql/conf.d/custom.cnf:ro"
      - "./docker/mysql/database:/var/lib/mysql"
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=development

  phpmyadmin:
    image: library/phpmyadmin
    container_name: docker-php8-phpmyadmin
    tty: true
    depends_on:
      - mysql
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_HOSTS: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
  #  postgres:
  #    image: library/postgres:13-alpine
  #    container_name: docker-php8-postgres
  #    tty: true
  #    restart: always
  #    ports:
  #      - '5432:5432'
  #    volumes:
  #      - './docker/postgres:/var/lib/postgresql/data'
  #    environment:
  #      - POSTGRES_USER=root
  #      - POSTGRES_PASSWORD=root
  #      - POSTGRES_DB=development

  #  redis:
  #    image: bitnami/redis:latest
  #    restart: always
  #    tty: true
  #    container_name: docker-php8-redis
  #    volumes:
  #      - ./docker/redis:/bitnami/redis/data
  #    environment:
  #      - ALLOW_EMPTY_PASSWORD=no
  #      - REDIS_PASSWORD=root
  #    ports:
  #      - '6379:6379'
